db:
  name: org.mariadb.jdbc.Driver
  user: user_user
  password: 0jo
  url: jdbc:mariadb://192.168.0.100:3306/open_wifi
api:
  url: http://openapi.seoul.go.kr:8088
  name: TbPublicWifiInfo
  key: 4a43487157647564363443444c5748
  type: json
  encoding: UTF-8
